apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-docker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins-docker
  template:
    metadata:
      labels:
        app: jenkins-docker
    spec:
      containers:
        - name: docker-image
          image: ankush8421/my-app-2.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-docker
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jenkins-docker
